[platformio]
name = Audio_Signal_Visualiser
default_envs = esp32dev

[env:esp32dev]
platform = espressif32 @ ^6.10.0
board = esp32dev
framework = arduino

monitor_speed  = 115200
upload_speed   = 921600
monitor_filters = time, colorize

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.12.2
  adafruit/Adafruit ILI9341    @ ^1.6.2

; Ignore any stray esp-dsp in libdeps; we use the one bundled in the core.
lib_ignore = esp-dsp

build_flags =
  -O3
  -ffast-math
  -DESP_PLATFORM
